# Generated by Django 5.1.14 on 2026-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0084_botmediarequest_mute_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="delivery_attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_enqueued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_failure_data",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="delivery_state",
            field=models.IntegerField(
                choices=[
                    (1, "Not Started"),
                    (2, "Staged"),
                    (3, "Uploading"),
                    (4, "Ready"),
                    (5, "Failed"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="duration_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="external_storage_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="file_sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="file_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="is_partial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recording",
            name="local_file_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="webhookdeliveryattempt",
            name="webhook_trigger_type",
            field=models.IntegerField(
                choices=[
                    (1, "Bot State Change"),
                    (2, "Transcript Update"),
                    (3, "Chat Messages Update"),
                    (4, "Participant Join/Leave"),
                    (5, "Calendar Events Update"),
                    (6, "Calendar State Change"),
                    (7, "Async Transcription State Change"),
                    (8, "Zoom OAuth Connection State Change"),
                    (9, "Bot Logs Update"),
                    (10, "Participant Speech Start/Stop"),
                    (11, "Recording Ready"),
                ],
                default=1,
            ),
        ),
    ]
