# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0084_botmediarequest_mute_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="external_transcription_job_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
